<<<<<<< HEAD
"""
Generated manually to satisfy migration dependency
"""
from django.db import migrations
=======
# Generated by Django 6.0.7 on 2026-07-22 19:55

import django.utils.timezone
from django.db import migrations, models
>>>>>>> cb795687d9cddeaa5bceb740fa2dbfe50e086565


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
<<<<<<< HEAD
        # Intentionally empty: acts as a no-op placeholder for the missing 0002 migration.
=======
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=600),
        ),
>>>>>>> cb795687d9cddeaa5bceb740fa2dbfe50e086565
    ]
